user_pd: dict = {
    "referral": None,
    "first_start": None,
    "accept_date": None,
    "tg_username": None,
    "tg_fullname": None,
    "lang_tg": None,
    "lang": None,
    "tasks": None,
    "reject": 0,
    "total_sent": 0,
    "last_sent": None,
    "status": None,
    "fio": None,
    "age": None,
    "gender": None,
    "country": None,
    "race": None,
}
